(cl:in-package marine_acoustic_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          VELOCITY_MODE-VAL
          VELOCITY_MODE
          DVL_TYPE-VAL
          DVL_TYPE
          VELOCITY-VAL
          VELOCITY
          VELOCITY_COVAR-VAL
          VELOCITY_COVAR
          ALTITUDE-VAL
          ALTITUDE
          COURSE_GND-VAL
          COURSE_GND
          SPEED_GND-VAL
          SPEED_GND
          NUM_GOOD_BEAMS-VAL
          NUM_GOOD_BEAMS
          SOUND_SPEED-VAL
          SOUND_SPEED
          BEAM_RANGES_VALID-VAL
          BEAM_RANGES_VALID
          BEAM_VELOCITIES_VALID-VAL
          BEAM_VELOCITIES_VALID
          BEAM_UNIT_VEC-VAL
          BEAM_UNIT_VEC
          RANGE-VAL
          RANGE
          RANGE_COVAR-VAL
          RANGE_COVAR
          BEAM_QUALITY-VAL
          BEAM_QUALITY
          BEAM_VELOCITY-VAL
          BEAM_VELOCITY
          BEAM_VELOCITY_COVAR-VAL
          BEAM_VELOCITY_COVAR
))