(cl:defpackage marine_acoustic_msgs-msg
  (:use )
  (:export
   "<DETECTIONFLAG>"
   "DETECTIONFLAG"
   "<DVL>"
   "DVL"
   "<PINGINFO>"
   "PINGINFO"
   "<PROJECTEDSONARIMAGE>"
   "PROJECTEDSONARIMAGE"
   "<RAWSONARIMAGE>"
   "RAWSONARIMAGE"
   "<SONARDETECTIONS>"
   "SONARDETECTIONS"
   "<SONARIMAGEDATA>"
   "SONARIMAGEDATA"
   "<SONARRANGES>"
   "SONARRANGES"
  ))

