; Auto-generated. Do not edit!


(cl:in-package marine_acoustic_msgs-msg)


;//! \htmlinclude SonarDetections.msg.html

(cl:defclass <SonarDetections> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (ping_info
    :reader ping_info
    :initarg :ping_info
    :type marine_acoustic_msgs-msg:PingInfo
    :initform (cl:make-instance 'marine_acoustic_msgs-msg:PingInfo))
   (flags
    :reader flags
    :initarg :flags
    :type (cl:vector marine_acoustic_msgs-msg:DetectionFlag)
   :initform (cl:make-array 0 :element-type 'marine_acoustic_msgs-msg:DetectionFlag :initial-element (cl:make-instance 'marine_acoustic_msgs-msg:DetectionFlag)))
   (two_way_travel_times
    :reader two_way_travel_times
    :initarg :two_way_travel_times
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (tx_delays
    :reader tx_delays
    :initarg :tx_delays
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (intensities
    :reader intensities
    :initarg :intensities
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (tx_angles
    :reader tx_angles
    :initarg :tx_angles
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (rx_angles
    :reader rx_angles
    :initarg :rx_angles
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass SonarDetections (<SonarDetections>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SonarDetections>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SonarDetections)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name marine_acoustic_msgs-msg:<SonarDetections> is deprecated: use marine_acoustic_msgs-msg:SonarDetections instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <SonarDetections>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader marine_acoustic_msgs-msg:header-val is deprecated.  Use marine_acoustic_msgs-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'ping_info-val :lambda-list '(m))
(cl:defmethod ping_info-val ((m <SonarDetections>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader marine_acoustic_msgs-msg:ping_info-val is deprecated.  Use marine_acoustic_msgs-msg:ping_info instead.")
  (ping_info m))

(cl:ensure-generic-function 'flags-val :lambda-list '(m))
(cl:defmethod flags-val ((m <SonarDetections>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader marine_acoustic_msgs-msg:flags-val is deprecated.  Use marine_acoustic_msgs-msg:flags instead.")
  (flags m))

(cl:ensure-generic-function 'two_way_travel_times-val :lambda-list '(m))
(cl:defmethod two_way_travel_times-val ((m <SonarDetections>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader marine_acoustic_msgs-msg:two_way_travel_times-val is deprecated.  Use marine_acoustic_msgs-msg:two_way_travel_times instead.")
  (two_way_travel_times m))

(cl:ensure-generic-function 'tx_delays-val :lambda-list '(m))
(cl:defmethod tx_delays-val ((m <SonarDetections>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader marine_acoustic_msgs-msg:tx_delays-val is deprecated.  Use marine_acoustic_msgs-msg:tx_delays instead.")
  (tx_delays m))

(cl:ensure-generic-function 'intensities-val :lambda-list '(m))
(cl:defmethod intensities-val ((m <SonarDetections>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader marine_acoustic_msgs-msg:intensities-val is deprecated.  Use marine_acoustic_msgs-msg:intensities instead.")
  (intensities m))

(cl:ensure-generic-function 'tx_angles-val :lambda-list '(m))
(cl:defmethod tx_angles-val ((m <SonarDetections>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader marine_acoustic_msgs-msg:tx_angles-val is deprecated.  Use marine_acoustic_msgs-msg:tx_angles instead.")
  (tx_angles m))

(cl:ensure-generic-function 'rx_angles-val :lambda-list '(m))
(cl:defmethod rx_angles-val ((m <SonarDetections>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader marine_acoustic_msgs-msg:rx_angles-val is deprecated.  Use marine_acoustic_msgs-msg:rx_angles instead.")
  (rx_angles m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SonarDetections>) ostream)
  "Serializes a message object of type '<SonarDetections>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'ping_info) ostream)
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'flags))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'flags))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'two_way_travel_times))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'two_way_travel_times))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'tx_delays))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'tx_delays))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'intensities))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'intensities))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'tx_angles))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'tx_angles))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'rx_angles))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-single-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)))
   (cl:slot-value msg 'rx_angles))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SonarDetections>) istream)
  "Deserializes a message object of type '<SonarDetections>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'ping_info) istream)
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'flags) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'flags)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'marine_acoustic_msgs-msg:DetectionFlag))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'two_way_travel_times) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'two_way_travel_times)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'tx_delays) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'tx_delays)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'intensities) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'intensities)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'tx_angles) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'tx_angles)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'rx_angles) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'rx_angles)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-single-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SonarDetections>)))
  "Returns string type for a message object of type '<SonarDetections>"
  "marine_acoustic_msgs/SonarDetections")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SonarDetections)))
  "Returns string type for a message object of type 'SonarDetections"
  "marine_acoustic_msgs/SonarDetections")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SonarDetections>)))
  "Returns md5sum for a message object of type '<SonarDetections>"
  "588993519ccaab99fb0df80256b440ff")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SonarDetections)))
  "Returns md5sum for a message object of type 'SonarDetections"
  "588993519ccaab99fb0df80256b440ff")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SonarDetections>)))
  "Returns full string definition for message of type '<SonarDetections>"
  (cl:format cl:nil "# Single ping from a multibeam sonar.~%#~%# This message is modeled after WHOI's MultibeamRaw.msg, from the~%# ds_multibeam_msgs package (released under a BSD license).~%# Modifications were made by UW-APL.~%~%# The header time should be the time the ping was transmitted, not~%# the time the message was received.~%# Note that these two could potentially be several seconds apart,~%# especially in deep water.~%std_msgs/Header header~%~%PingInfo ping_info~%~%# Constants declaring whether each beam is good or bad.~%# This is implemented as an 8-bit masked value; it is possible for more~%# than one thing to flag beams as bad. To check if a beam is good, simply~%# check if it is zero.~%~%DetectionFlag[] flags~%~%# Truly raw multibeam data uses travel times rather than ranges.~%# reported in seconds~%float32[] two_way_travel_times~%~%# Multi-sector multibeams can transmit different sectors at different times~%# The Reson doesn't but we include a TX delay for each beam anyway.~%#~%# Overall, therefore, our overall time is:~%#~%# header.stamp: TX cycle starts~%# Each beam's TX time: header.stamp + txDelay[i]~%# Each beam's RX time: header.stamp + txDelay[i] + twowayTravelTime[i]~%# reported in seconds~%float32[] tx_delays~%~%# Sonar-reported intensity.  Usually uncalibrated and crude~%float32[] intensities~%~%# Sonar-reported along-track steering angle (applied to tx beam)~%# + forward, - aft for a downlooking sonar~%# reported in radians~%float32[] tx_angles~%~%# Sonar-reported across-track steering angle (applied to rx beam)~%# + to starboard, - to port for a downlooking sonar~%# reported in radians~%float32[] rx_angles~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: marine_acoustic_msgs/PingInfo~%# Center frequency of sonar in Hz~%# Set to 0 if unavailable~%float32 frequency~%~%# Speed of sound (m/s) used to calculate ranges;~%# Set to 0 if unavailable~%float32 sound_speed~%~%# Sonar reported -3db beamwidths~%# May be empty if not reported~%# reported in radians~%float32[] tx_beamwidths~%float32[] rx_beamwidths~%~%================================================================================~%MSG: marine_acoustic_msgs/DetectionFlag~%# Beam is OK~%uint8 DETECT_OK = 0~%# Beam is flagged as bad by the sonar.  Think hard before second-guessing~%uint8 DETECT_BAD_SONAR = 1~%# Beam is flagged as bad by some automated filter applied during processing.~%uint8 DETECT_BAD_FILTER = 2~%# Beam is flagged as bad by the user. This is probably not happening in~%# realtime, but is included here so the same message can be used throughout~%# a post-processing pipeline.~%uint8 DETECT_BAD_USER = 4~%~%# These arrays should have the same dimensions, and should match~%# the number of beams for this sonar.~%#~%# Some fields are optional.  Those should have 0 length.~%~%# Flag values for every beam~%uint8 flag~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SonarDetections)))
  "Returns full string definition for message of type 'SonarDetections"
  (cl:format cl:nil "# Single ping from a multibeam sonar.~%#~%# This message is modeled after WHOI's MultibeamRaw.msg, from the~%# ds_multibeam_msgs package (released under a BSD license).~%# Modifications were made by UW-APL.~%~%# The header time should be the time the ping was transmitted, not~%# the time the message was received.~%# Note that these two could potentially be several seconds apart,~%# especially in deep water.~%std_msgs/Header header~%~%PingInfo ping_info~%~%# Constants declaring whether each beam is good or bad.~%# This is implemented as an 8-bit masked value; it is possible for more~%# than one thing to flag beams as bad. To check if a beam is good, simply~%# check if it is zero.~%~%DetectionFlag[] flags~%~%# Truly raw multibeam data uses travel times rather than ranges.~%# reported in seconds~%float32[] two_way_travel_times~%~%# Multi-sector multibeams can transmit different sectors at different times~%# The Reson doesn't but we include a TX delay for each beam anyway.~%#~%# Overall, therefore, our overall time is:~%#~%# header.stamp: TX cycle starts~%# Each beam's TX time: header.stamp + txDelay[i]~%# Each beam's RX time: header.stamp + txDelay[i] + twowayTravelTime[i]~%# reported in seconds~%float32[] tx_delays~%~%# Sonar-reported intensity.  Usually uncalibrated and crude~%float32[] intensities~%~%# Sonar-reported along-track steering angle (applied to tx beam)~%# + forward, - aft for a downlooking sonar~%# reported in radians~%float32[] tx_angles~%~%# Sonar-reported across-track steering angle (applied to rx beam)~%# + to starboard, - to port for a downlooking sonar~%# reported in radians~%float32[] rx_angles~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: marine_acoustic_msgs/PingInfo~%# Center frequency of sonar in Hz~%# Set to 0 if unavailable~%float32 frequency~%~%# Speed of sound (m/s) used to calculate ranges;~%# Set to 0 if unavailable~%float32 sound_speed~%~%# Sonar reported -3db beamwidths~%# May be empty if not reported~%# reported in radians~%float32[] tx_beamwidths~%float32[] rx_beamwidths~%~%================================================================================~%MSG: marine_acoustic_msgs/DetectionFlag~%# Beam is OK~%uint8 DETECT_OK = 0~%# Beam is flagged as bad by the sonar.  Think hard before second-guessing~%uint8 DETECT_BAD_SONAR = 1~%# Beam is flagged as bad by some automated filter applied during processing.~%uint8 DETECT_BAD_FILTER = 2~%# Beam is flagged as bad by the user. This is probably not happening in~%# realtime, but is included here so the same message can be used throughout~%# a post-processing pipeline.~%uint8 DETECT_BAD_USER = 4~%~%# These arrays should have the same dimensions, and should match~%# the number of beams for this sonar.~%#~%# Some fields are optional.  Those should have 0 length.~%~%# Flag values for every beam~%uint8 flag~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SonarDetections>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'ping_info))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'flags) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'two_way_travel_times) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'tx_delays) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'intensities) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'tx_angles) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'rx_angles) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 4)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SonarDetections>))
  "Converts a ROS message object to a list"
  (cl:list 'SonarDetections
    (cl:cons ':header (header msg))
    (cl:cons ':ping_info (ping_info msg))
    (cl:cons ':flags (flags msg))
    (cl:cons ':two_way_travel_times (two_way_travel_times msg))
    (cl:cons ':tx_delays (tx_delays msg))
    (cl:cons ':intensities (intensities msg))
    (cl:cons ':tx_angles (tx_angles msg))
    (cl:cons ':rx_angles (rx_angles msg))
))
