// Generated by gencpp from file marine_acoustic_msgs/Dvl.msg
// DO NOT EDIT!


#ifndef MARINE_ACOUSTIC_MSGS_MESSAGE_DVL_H
#define MARINE_ACOUSTIC_MSGS_MESSAGE_DVL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace marine_acoustic_msgs
{
template <class ContainerAllocator>
struct Dvl_
{
  typedef Dvl_<ContainerAllocator> Type;

  Dvl_()
    : header()
    , velocity_mode(0)
    , dvl_type(0)
    , velocity()
    , velocity_covar()
    , altitude(0.0)
    , course_gnd(0.0)
    , speed_gnd(0.0)
    , num_good_beams(0)
    , sound_speed(0.0)
    , beam_ranges_valid(false)
    , beam_velocities_valid(false)
    , beam_unit_vec()
    , range()
    , range_covar()
    , beam_quality()
    , beam_velocity()
    , beam_velocity_covar()  {
      velocity_covar.assign(0.0);

      range.assign(0.0);

      range_covar.assign(0.0);

      beam_quality.assign(0.0);

      beam_velocity.assign(0.0);

      beam_velocity_covar.assign(0.0);
  }
  Dvl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , velocity_mode(0)
    , dvl_type(0)
    , velocity(_alloc)
    , velocity_covar()
    , altitude(0.0)
    , course_gnd(0.0)
    , speed_gnd(0.0)
    , num_good_beams(0)
    , sound_speed(0.0)
    , beam_ranges_valid(false)
    , beam_velocities_valid(false)
    , beam_unit_vec()
    , range()
    , range_covar()
    , beam_quality()
    , beam_velocity()
    , beam_velocity_covar()  {
  (void)_alloc;
      velocity_covar.assign(0.0);

      beam_unit_vec.assign( ::geometry_msgs::Vector3_<ContainerAllocator> (_alloc));

      range.assign(0.0);

      range_covar.assign(0.0);

      beam_quality.assign(0.0);

      beam_velocity.assign(0.0);

      beam_velocity_covar.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _velocity_mode_type;
  _velocity_mode_type velocity_mode;

   typedef uint8_t _dvl_type_type;
  _dvl_type_type dvl_type;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef boost::array<double, 9>  _velocity_covar_type;
  _velocity_covar_type velocity_covar;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _course_gnd_type;
  _course_gnd_type course_gnd;

   typedef double _speed_gnd_type;
  _speed_gnd_type speed_gnd;

   typedef uint8_t _num_good_beams_type;
  _num_good_beams_type num_good_beams;

   typedef float _sound_speed_type;
  _sound_speed_type sound_speed;

   typedef uint8_t _beam_ranges_valid_type;
  _beam_ranges_valid_type beam_ranges_valid;

   typedef uint8_t _beam_velocities_valid_type;
  _beam_velocities_valid_type beam_velocities_valid;

   typedef boost::array< ::geometry_msgs::Vector3_<ContainerAllocator> , 4>  _beam_unit_vec_type;
  _beam_unit_vec_type beam_unit_vec;

   typedef boost::array<double, 4>  _range_type;
  _range_type range;

   typedef boost::array<float, 4>  _range_covar_type;
  _range_covar_type range_covar;

   typedef boost::array<float, 4>  _beam_quality_type;
  _beam_quality_type beam_quality;

   typedef boost::array<float, 4>  _beam_velocity_type;
  _beam_velocity_type beam_velocity;

   typedef boost::array<float, 4>  _beam_velocity_covar_type;
  _beam_velocity_covar_type beam_velocity_covar;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(DVL_MODE_BOTTOM)
  #undef DVL_MODE_BOTTOM
#endif
#if defined(_WIN32) && defined(DVL_MODE_WATER)
  #undef DVL_MODE_WATER
#endif
#if defined(_WIN32) && defined(DVL_TYPE_PISTON)
  #undef DVL_TYPE_PISTON
#endif
#if defined(_WIN32) && defined(DVL_TYPE_PHASED_ARRAY)
  #undef DVL_TYPE_PHASED_ARRAY
#endif

  enum {
    DVL_MODE_BOTTOM = 1u,
    DVL_MODE_WATER = 2u,
    DVL_TYPE_PISTON = 0u,
    DVL_TYPE_PHASED_ARRAY = 1u,
  };


  typedef boost::shared_ptr< ::marine_acoustic_msgs::Dvl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marine_acoustic_msgs::Dvl_<ContainerAllocator> const> ConstPtr;

}; // struct Dvl_

typedef ::marine_acoustic_msgs::Dvl_<std::allocator<void> > Dvl;

typedef boost::shared_ptr< ::marine_acoustic_msgs::Dvl > DvlPtr;
typedef boost::shared_ptr< ::marine_acoustic_msgs::Dvl const> DvlConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marine_acoustic_msgs::Dvl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marine_acoustic_msgs::Dvl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marine_acoustic_msgs::Dvl_<ContainerAllocator1> & lhs, const ::marine_acoustic_msgs::Dvl_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.velocity_mode == rhs.velocity_mode &&
    lhs.dvl_type == rhs.dvl_type &&
    lhs.velocity == rhs.velocity &&
    lhs.velocity_covar == rhs.velocity_covar &&
    lhs.altitude == rhs.altitude &&
    lhs.course_gnd == rhs.course_gnd &&
    lhs.speed_gnd == rhs.speed_gnd &&
    lhs.num_good_beams == rhs.num_good_beams &&
    lhs.sound_speed == rhs.sound_speed &&
    lhs.beam_ranges_valid == rhs.beam_ranges_valid &&
    lhs.beam_velocities_valid == rhs.beam_velocities_valid &&
    lhs.beam_unit_vec == rhs.beam_unit_vec &&
    lhs.range == rhs.range &&
    lhs.range_covar == rhs.range_covar &&
    lhs.beam_quality == rhs.beam_quality &&
    lhs.beam_velocity == rhs.beam_velocity &&
    lhs.beam_velocity_covar == rhs.beam_velocity_covar;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marine_acoustic_msgs::Dvl_<ContainerAllocator1> & lhs, const ::marine_acoustic_msgs::Dvl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marine_acoustic_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::marine_acoustic_msgs::Dvl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marine_acoustic_msgs::Dvl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marine_acoustic_msgs::Dvl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marine_acoustic_msgs::Dvl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marine_acoustic_msgs::Dvl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marine_acoustic_msgs::Dvl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marine_acoustic_msgs::Dvl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f09bbfba6f467f84523073fb27d38e3e";
  }

  static const char* value(const ::marine_acoustic_msgs::Dvl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf09bbfba6f467f84ULL;
  static const uint64_t static_value2 = 0x523073fb27d38e3eULL;
};

template<class ContainerAllocator>
struct DataType< ::marine_acoustic_msgs::Dvl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marine_acoustic_msgs/Dvl";
  }

  static const char* value(const ::marine_acoustic_msgs::Dvl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marine_acoustic_msgs::Dvl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Message for single ground-track ping from a DVL.\n"
"#\n"
"# This message is modeled after WHOI's Dvl.msg from the ds_sensor_msgs\n"
"# repository, which was released under a BSD license.\n"
"# Modifications were made by UW-APL.\n"
"\n"
"# ENUM: Velocity mode\n"
"uint8 DVL_MODE_BOTTOM=1\n"
"uint8 DVL_MODE_WATER=2\n"
"\n"
"# ENUM: DVL Type; used in sound velocity corrections\n"
"\n"
"# Standard (Janus) array with one piston transducer for each beam.\n"
"# If you have 4-5 individual disks on your DVL, use this one.\n"
"# Examples include Sonardyne Syrinx, Nortek DVLs, and RDI Workhorse\n"
"uint8 DVL_TYPE_PISTON=0\n"
"\n"
"# Phased-array DVL.  If you have one giant disk with complicated stuff\n"
"# on it, probably this one.\n"
"# Examples include newer RDI DVLs such as pathfinder, pioneer, and tasman.\n"
"uint8 DVL_TYPE_PHASED_ARRAY=1\n"
"\n"
"# The standard ROS header.\n"
"# Timestamp is neither transmit nor receive time -- it is the time that\n"
"# the velocity should be considered valid at.\n"
"# Frame convention:\n"
"# * z-axis in direction DVL is pointing\n"
"# * x-axis aligned with vehicle forward\n"
"std_msgs/Header header\n"
"\n"
"# Velocity mode (see above)\n"
"uint8 velocity_mode\n"
"\n"
"# Type of DVL array employed (see above).  Necessary when\n"
"# deciding how to apply sound velocity corrections\n"
"uint8 dvl_type\n"
"\n"
"# Velocities [m/s]\n"
"geometry_msgs/Vector3 velocity\n"
"\n"
"# row-major, xyz axes.  Set to \"-1\" if not known.\n"
"float64[9] velocity_covar\n"
"\n"
"# Average altitude of all good beam returns.\n"
"# For 30-deg sensor, altitude = (sqrt(3) / 2) * sum(range) / num_good_beams\n"
"float64 altitude\n"
"# Calculated from xy velocities: course_gnd = atan2(velocity.y, velocity.x)\n"
"float64 course_gnd\n"
"# Calculated from xy velocities: speed_gnd = sqrt(velocity.x^2 + velocity.y^2)\n"
"float64 speed_gnd\n"
"\n"
"uint8 num_good_beams\n"
"\n"
"# Speed of sound (m/s) used by the DVL\n"
"float32 sound_speed\n"
"\n"
"# Beam data\n"
"# Some DVLs/DVL configurations only report the derived velocities.\n"
"bool beam_ranges_valid\n"
"bool beam_velocities_valid\n"
"\n"
"# Geometry of each of the 4 beams\n"
"geometry_msgs/Vector3[4] beam_unit_vec\n"
"\n"
"# beam_unit_vec[i] * range[i] is the point where the beam hits the seafloor.\n"
"# For a 30-deg sensor, multiply by sqrt(3)/2 to get altitude.\n"
"float64[4] range\n"
"float32[4] range_covar\n"
"\n"
"# Beam quality flag.\n"
"# The meaning of this flag is DVL-specific (at least for now).\n"
"float32[4] beam_quality\n"
"\n"
"# Raw velocities for each beam [m/s].\n"
"# Will be beam 1,2,3,4 velocity in beam coordinates\n"
"float32[4] beam_velocity\n"
"# Covariance, as always, should be -1 if unknown\n"
"float32[4] beam_velocity_covar\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::marine_acoustic_msgs::Dvl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marine_acoustic_msgs::Dvl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.velocity_mode);
      stream.next(m.dvl_type);
      stream.next(m.velocity);
      stream.next(m.velocity_covar);
      stream.next(m.altitude);
      stream.next(m.course_gnd);
      stream.next(m.speed_gnd);
      stream.next(m.num_good_beams);
      stream.next(m.sound_speed);
      stream.next(m.beam_ranges_valid);
      stream.next(m.beam_velocities_valid);
      stream.next(m.beam_unit_vec);
      stream.next(m.range);
      stream.next(m.range_covar);
      stream.next(m.beam_quality);
      stream.next(m.beam_velocity);
      stream.next(m.beam_velocity_covar);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Dvl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marine_acoustic_msgs::Dvl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marine_acoustic_msgs::Dvl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "velocity_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.velocity_mode);
    s << indent << "dvl_type: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dvl_type);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "velocity_covar[]" << std::endl;
    for (size_t i = 0; i < v.velocity_covar.size(); ++i)
    {
      s << indent << "  velocity_covar[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velocity_covar[i]);
    }
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "course_gnd: ";
    Printer<double>::stream(s, indent + "  ", v.course_gnd);
    s << indent << "speed_gnd: ";
    Printer<double>::stream(s, indent + "  ", v.speed_gnd);
    s << indent << "num_good_beams: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.num_good_beams);
    s << indent << "sound_speed: ";
    Printer<float>::stream(s, indent + "  ", v.sound_speed);
    s << indent << "beam_ranges_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.beam_ranges_valid);
    s << indent << "beam_velocities_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.beam_velocities_valid);
    s << indent << "beam_unit_vec[]" << std::endl;
    for (size_t i = 0; i < v.beam_unit_vec.size(); ++i)
    {
      s << indent << "  beam_unit_vec[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.beam_unit_vec[i]);
    }
    s << indent << "range[]" << std::endl;
    for (size_t i = 0; i < v.range.size(); ++i)
    {
      s << indent << "  range[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.range[i]);
    }
    s << indent << "range_covar[]" << std::endl;
    for (size_t i = 0; i < v.range_covar.size(); ++i)
    {
      s << indent << "  range_covar[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.range_covar[i]);
    }
    s << indent << "beam_quality[]" << std::endl;
    for (size_t i = 0; i < v.beam_quality.size(); ++i)
    {
      s << indent << "  beam_quality[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.beam_quality[i]);
    }
    s << indent << "beam_velocity[]" << std::endl;
    for (size_t i = 0; i < v.beam_velocity.size(); ++i)
    {
      s << indent << "  beam_velocity[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.beam_velocity[i]);
    }
    s << indent << "beam_velocity_covar[]" << std::endl;
    for (size_t i = 0; i < v.beam_velocity_covar.size(); ++i)
    {
      s << indent << "  beam_velocity_covar[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.beam_velocity_covar[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARINE_ACOUSTIC_MSGS_MESSAGE_DVL_H
