// Generated by gencpp from file marine_acoustic_msgs/ProjectedSonarImage.msg
// DO NOT EDIT!


#ifndef MARINE_ACOUSTIC_MSGS_MESSAGE_PROJECTEDSONARIMAGE_H
#define MARINE_ACOUSTIC_MSGS_MESSAGE_PROJECTEDSONARIMAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <marine_acoustic_msgs/PingInfo.h>
#include <geometry_msgs/Vector3.h>
#include <marine_acoustic_msgs/SonarImageData.h>

namespace marine_acoustic_msgs
{
template <class ContainerAllocator>
struct ProjectedSonarImage_
{
  typedef ProjectedSonarImage_<ContainerAllocator> Type;

  ProjectedSonarImage_()
    : header()
    , ping_info()
    , beam_directions()
    , ranges()
    , image()  {
    }
  ProjectedSonarImage_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , ping_info(_alloc)
    , beam_directions(_alloc)
    , ranges(_alloc)
    , image(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::marine_acoustic_msgs::PingInfo_<ContainerAllocator>  _ping_info_type;
  _ping_info_type ping_info;

   typedef std::vector< ::geometry_msgs::Vector3_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Vector3_<ContainerAllocator> >> _beam_directions_type;
  _beam_directions_type beam_directions;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _ranges_type;
  _ranges_type ranges;

   typedef  ::marine_acoustic_msgs::SonarImageData_<ContainerAllocator>  _image_type;
  _image_type image;





  typedef boost::shared_ptr< ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator> const> ConstPtr;

}; // struct ProjectedSonarImage_

typedef ::marine_acoustic_msgs::ProjectedSonarImage_<std::allocator<void> > ProjectedSonarImage;

typedef boost::shared_ptr< ::marine_acoustic_msgs::ProjectedSonarImage > ProjectedSonarImagePtr;
typedef boost::shared_ptr< ::marine_acoustic_msgs::ProjectedSonarImage const> ProjectedSonarImageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator1> & lhs, const ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.ping_info == rhs.ping_info &&
    lhs.beam_directions == rhs.beam_directions &&
    lhs.ranges == rhs.ranges &&
    lhs.image == rhs.image;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator1> & lhs, const ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace marine_acoustic_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c72fc8e29ab227a547720a36666022fd";
  }

  static const char* value(const ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc72fc8e29ab227a5ULL;
  static const uint64_t static_value2 = 0x47720a36666022fdULL;
};

template<class ContainerAllocator>
struct DataType< ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "marine_acoustic_msgs/ProjectedSonarImage";
  }

  static const char* value(const ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Single scan from an imaging sonar\n"
"#\n"
"# The Z-axis is centered in the plane of the fan (\"forward\"), with X up,\n"
"# in order to be consistent with the NED for traditional multibeam profilers.\n"
"#\n"
"# For sonars with a 1D array, the beams lie on the Y-Z plane, and\n"
"# and each beam has an azimuth (rotation about X) value.  Zero azimuth\n"
"# is in the direction of the Z-axis, typically \"straight out\" from the sonar.\n"
"# Elevation is the orthogonal direction (rotation about Y),\n"
"# often termed the \"vertical aperture\"\n"
"\n"
"# The header time should be the time the ping was transmitted, not\n"
"# the time the message was received.\n"
"# Note that these two could potentially be several seconds apart,\n"
"# especially in deep water.\n"
"std_msgs/Header header\n"
"\n"
"PingInfo ping_info\n"
"\n"
"geometry_msgs/Vector3[] beam_directions\n"
"\n"
"# Center of each range bin in meters. Note this these may not be equally\n"
"# spaced, and do not necessarily start at zero range.\n"
"float32[] ranges\n"
"\n"
"SonarImageData image\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: marine_acoustic_msgs/PingInfo\n"
"# Center frequency of sonar in Hz\n"
"# Set to 0 if unavailable\n"
"float32 frequency\n"
"\n"
"# Speed of sound (m/s) used to calculate ranges;\n"
"# Set to 0 if unavailable\n"
"float32 sound_speed\n"
"\n"
"# Sonar reported -3db beamwidths\n"
"# May be empty if not reported\n"
"# reported in radians\n"
"float32[] tx_beamwidths\n"
"float32[] rx_beamwidths\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: marine_acoustic_msgs/SonarImageData\n"
"bool    is_bigendian\n"
"\n"
"uint32  DTYPE_UINT8 = 0\n"
"uint32  DTYPE_INT8 = 1\n"
"uint32  DTYPE_UINT16 = 2\n"
"uint32  DTYPE_INT16 = 3\n"
"uint32  DTYPE_UINT32 = 4\n"
"uint32  DTYPE_INT32 = 5\n"
"uint32  DTYPE_UINT64 = 6\n"
"uint32  DTYPE_INT64 = 7\n"
"uint32  DTYPE_FLOAT32 = 8\n"
"uint32  DTYPE_FLOAT64 = 9\n"
"\n"
"uint32  dtype\n"
"\n"
"# the number of beams associated with the image\n"
"uint32 beam_count\n"
"\n"
"# The actually pixel data in row-major (beam_index major) format\n"
"uint8[] data\n"
;
  }

  static const char* value(const ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.ping_info);
      stream.next(m.beam_directions);
      stream.next(m.ranges);
      stream.next(m.image);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProjectedSonarImage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::marine_acoustic_msgs::ProjectedSonarImage_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "ping_info: ";
    s << std::endl;
    Printer< ::marine_acoustic_msgs::PingInfo_<ContainerAllocator> >::stream(s, indent + "  ", v.ping_info);
    s << indent << "beam_directions[]" << std::endl;
    for (size_t i = 0; i < v.beam_directions.size(); ++i)
    {
      s << indent << "  beam_directions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "    ", v.beam_directions[i]);
    }
    s << indent << "ranges[]" << std::endl;
    for (size_t i = 0; i < v.ranges.size(); ++i)
    {
      s << indent << "  ranges[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ranges[i]);
    }
    s << indent << "image: ";
    s << std::endl;
    Printer< ::marine_acoustic_msgs::SonarImageData_<ContainerAllocator> >::stream(s, indent + "  ", v.image);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MARINE_ACOUSTIC_MSGS_MESSAGE_PROJECTEDSONARIMAGE_H
